# Generated by Django 3.1.7 on 2021-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Refund', 'Refund'), ('Withdrawal', 'Withdrawal')], default='Purchase', max_length=64),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
