# Generated by Django 3.1.7 on 2021-03-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210331_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='transaction_type',
            new_name='operation_type',
        ),
    ]
